### ISSUE TITLE
Over socks or using onion services?

### ISSUE THREAD

**Issue by lostinblue** [Miserlou/OnionRTC#1]
Are you trying to route webRTC through hidden services or over socks5? I have been trying to get webRTC with onion services. If you want to combine efforts please reach out.

**Comment by Miserlou** [comment]
To be honest, nothing ever really came of this repo, and I think TBB is pretty crippled when it comes to WebRTC. Good luck in your adventures.

**Comment by lostinblue** [comment]
I was not suggesting using TBB, I don't think that would be ideal. I was thinking of just using a native webRTC client using the c library librtc and just building or using some other SIP client.

**Comment by Miserlou** [comment]
WebRTC can use TCP or UDP, so if you use it with both clients in TCP mode then I think that should work over Tor. I don't know what will happen when the circuits renegotiate. I'd be very interested to see your results. What's your application idea?
